# Generated by Django 5.2.6 on 2025-10-02 07:19

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_column="user_email", max_length=254, unique=True
                    ),
                ),
                (
                    "user_username",
                    models.CharField(
                        blank=True, db_column="user_username", max_length=150, null=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, db_column="user_firstname", max_length=150
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_column="user_lastname", max_length=150
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_column="user_is_active", default=True),
                ),
                (
                    "is_staff",
                    models.BooleanField(db_column="user_is_staff", default=False),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="user_date_joined"
                    ),
                ),
                (
                    "user_createtime",
                    models.DateTimeField(
                        auto_now_add=True, db_column="user_createtime", null=True
                    ),
                ),
                (
                    "user_detail",
                    models.TextField(blank=True, db_column="user_detail", default=""),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
                "db_table": "user_user",
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Function",
            fields=[
                ("func_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("func_name", models.CharField(max_length=255, unique=True)),
                ("func_detail", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Function",
                "verbose_name_plural": "Functions",
                "db_table": "function_lookup",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("func_name",), name="unique_function_func_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("mod_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mod_name", models.CharField(max_length=255, unique=True)),
                ("mod_detail", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "db_table": "module_lookup",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mod_name",), name="unique_module_mod_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FunctionModuleConnection",
            fields=[
                ("fmc_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "function",
                    models.ForeignKey(
                        db_column="func_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fmc_function_connections",
                        to="accounts.function",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        db_column="mod_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fmc_module_connections",
                        to="accounts.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "FunctionModuleConnection",
                "verbose_name_plural": "FunctionModuleConnections",
                "db_table": "function_module_connection",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=255, unique=True)),
                ("role_detail", models.TextField(blank=True, default="")),
                ("role_flag_delete", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "role_role",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role_name",), name="unique_role_role_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleFunctionModuleConnection",
            fields=[
                ("rfmc_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "fmc",
                    models.ForeignKey(
                        db_column="fmc_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfmc_fmc_connections",
                        to="accounts.functionmoduleconnection",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfmc_role_connections",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "RoleFunctionModuleConnection",
                "verbose_name_plural": "RoleFunctionModuleConnections",
                "db_table": "role_functionmoduleconnection",
            },
        ),
        migrations.CreateModel(
            name="RoleUserConnection",
            fields=[
                ("ruc_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userrole_connections",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roleuser_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RoleUserConnection",
                "verbose_name_plural": "RoleUserConnections",
                "db_table": "role_userconnection",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="user_user_email_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_username"], name="user_user_username_idx"),
        ),
        migrations.AddConstraint(
            model_name="functionmoduleconnection",
            constraint=models.UniqueConstraint(
                fields=("module", "function"), name="unique_module_function_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolefunctionmoduleconnection",
            constraint=models.UniqueConstraint(
                fields=("role", "fmc"), name="unique_role_fmc_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="roleuserconnection",
            constraint=models.UniqueConstraint(
                fields=("user", "role"), name="unique_user_role_pair"
            ),
        ),
    ]
